/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;



public class VentanaRegistrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistrarCliente
     */
    public VentanaRegistrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PestañaEditarClientes = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        NombresMsj = new javax.swing.JLabel();
        ApellidosMsj = new javax.swing.JLabel();
        BotonTomarFoto = new javax.swing.JButton();
        GuardarNacimiento = new javax.swing.JTextField();
        NacimientoMsj = new javax.swing.JLabel();
        GuardarTelefono = new javax.swing.JTextField();
        GuardarEstatura = new javax.swing.JTextField();
        GuardarPeso = new javax.swing.JTextField();
        GuardarOtros = new javax.swing.JTextField();
        TelefonoMsj = new javax.swing.JLabel();
        EstaturaMsj = new javax.swing.JLabel();
        PesoMsj = new javax.swing.JLabel();
        OtrosMsj = new javax.swing.JLabel();
        TelefonoMsj1 = new javax.swing.JLabel();
        OtrosMsj1 = new javax.swing.JLabel();
        GuardarOtros1 = new javax.swing.JTextField();
        GuardarOtros2 = new javax.swing.JTextField();
        GuardarOtros3 = new javax.swing.JTextField();
        GuardarOtros4 = new javax.swing.JTextField();
        BotonAgreHuella = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NombresMsj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombresMsj.setText("Nombres:");

        ApellidosMsj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ApellidosMsj.setText("Apellidos:");

        BotonTomarFoto.setText("FOTO");

        GuardarNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarNacimientoActionPerformed(evt);
            }
        });

        NacimientoMsj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NacimientoMsj.setText("Nacimiento:");

        GuardarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarTelefonoActionPerformed(evt);
            }
        });

        GuardarEstatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarEstaturaActionPerformed(evt);
            }
        });

        GuardarPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarPesoActionPerformed(evt);
            }
        });

        GuardarOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarOtrosActionPerformed(evt);
            }
        });

        TelefonoMsj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TelefonoMsj.setText("Telefono:");

        EstaturaMsj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EstaturaMsj.setText("Estatura:");

        PesoMsj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PesoMsj.setText("Peso:");

        OtrosMsj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OtrosMsj.setText("Otros:");

        TelefonoMsj1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TelefonoMsj1.setText("Correo:");

        OtrosMsj1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OtrosMsj1.setText("Sexo:");

        GuardarOtros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarOtros1ActionPerformed(evt);
            }
        });

        GuardarOtros2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarOtros2ActionPerformed(evt);
            }
        });

        GuardarOtros3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarOtros3ActionPerformed(evt);
            }
        });

        GuardarOtros4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarOtros4ActionPerformed(evt);
            }
        });

        BotonAgreHuella.setText("AGREGAR HUELLA");

        BotonSalir.setText("SALIR");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonGuardar.setText("GUARDAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OtrosMsj)
                    .addComponent(NacimientoMsj)
                    .addComponent(ApellidosMsj)
                    .addComponent(NombresMsj)
                    .addComponent(TelefonoMsj)
                    .addComponent(TelefonoMsj1)
                    .addComponent(OtrosMsj1)
                    .addComponent(EstaturaMsj)
                    .addComponent(PesoMsj))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GuardarPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardarOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardarEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardarOtros1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardarOtros3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardarOtros4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GuardarOtros2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GuardarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                                .addComponent(BotonAgreHuella, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(GuardarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonTomarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonGuardar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombresMsj)
                    .addComponent(GuardarOtros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidosMsj)
                    .addComponent(GuardarOtros2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NacimientoMsj)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GuardarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonTomarFoto)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoMsj)
                    .addComponent(GuardarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAgreHuella))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelefonoMsj1)
                    .addComponent(GuardarOtros3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OtrosMsj1)
                    .addComponent(GuardarOtros4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstaturaMsj)
                    .addComponent(GuardarEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesoMsj)
                    .addComponent(GuardarPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OtrosMsj))
                .addGap(16, 16, 16)
                .addComponent(BotonGuardar)
                .addGap(27, 27, 27)
                .addComponent(BotonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PestañaEditarClientes.addTab("Agregar Cliente", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 937, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        PestañaEditarClientes.addTab("Clientes", jPanel2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PestañaEditarClientes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PestañaEditarClientes)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarEstaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarEstaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarEstaturaActionPerformed

    private void GuardarNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarNacimientoActionPerformed

    private void GuardarOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarOtrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarOtrosActionPerformed

    private void GuardarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarTelefonoActionPerformed

    private void GuardarPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarPesoActionPerformed

    private void GuardarOtros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarOtros1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarOtros1ActionPerformed

    private void GuardarOtros2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarOtros2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarOtros2ActionPerformed

    private void GuardarOtros3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarOtros3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarOtros3ActionPerformed

    private void GuardarOtros4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarOtros4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarOtros4ActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidosMsj;
    private javax.swing.JButton BotonAgreHuella;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonTomarFoto;
    private javax.swing.JLabel EstaturaMsj;
    private javax.swing.JTextField GuardarEstatura;
    private javax.swing.JTextField GuardarNacimiento;
    private javax.swing.JTextField GuardarOtros;
    private javax.swing.JTextField GuardarOtros1;
    private javax.swing.JTextField GuardarOtros2;
    private javax.swing.JTextField GuardarOtros3;
    private javax.swing.JTextField GuardarOtros4;
    private javax.swing.JTextField GuardarPeso;
    private javax.swing.JTextField GuardarTelefono;
    private javax.swing.JLabel NacimientoMsj;
    private javax.swing.JLabel NombresMsj;
    private javax.swing.JLabel OtrosMsj;
    private javax.swing.JLabel OtrosMsj1;
    private javax.swing.JLabel PesoMsj;
    private javax.swing.JTabbedPane PestañaEditarClientes;
    private javax.swing.JLabel TelefonoMsj;
    private javax.swing.JLabel TelefonoMsj1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
